# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 18:07
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
